package DAO;
// Generated 12/04/2016 11:37:48 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int idu;
     private String nombre;
     private String apellidopaterno;
     private String apellidomaterno;
     private Set loggins = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(int idu) {
        this.idu = idu;
    }
    public Usuarios(int idu, String nombre, String apellidopaterno, String apellidomaterno, Set loggins) {
       this.idu = idu;
       this.nombre = nombre;
       this.apellidopaterno = apellidopaterno;
       this.apellidomaterno = apellidomaterno;
       this.loggins = loggins;
    }
   
    public int getIdu() {
        return this.idu;
    }
    
    public void setIdu(int idu) {
        this.idu = idu;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidopaterno() {
        return this.apellidopaterno;
    }
    
    public void setApellidopaterno(String apellidopaterno) {
        this.apellidopaterno = apellidopaterno;
    }
    public String getApellidomaterno() {
        return this.apellidomaterno;
    }
    
    public void setApellidomaterno(String apellidomaterno) {
        this.apellidomaterno = apellidomaterno;
    }
    public Set getLoggins() {
        return this.loggins;
    }
    
    public void setLoggins(Set loggins) {
        this.loggins = loggins;
    }




}


